# Generated by Django 4.1.1 on 2023-01-30 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrregularVerbs',
            fields=[
                ('word_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.word')),
                ('past_simple', models.CharField(max_length=128)),
                ('past_participle', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Verb',
                'verbose_name_plural': 'Verbs',
            },
            bases=('base.word',),
        ),
    ]
