# Generated by Django 3.2.16 on 2023-04-07 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryword',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.themes'),
        ),
    ]
