# Generated by Django 3.2.16 on 2023-04-07 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_categoryword_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryword',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='base.themes'),
        ),
    ]
