# Generated by Django 3.2.16 on 2023-04-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_categoryword_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='themes',
            name='frequency_word',
            field=models.BooleanField(default=False),
        ),
    ]
