# Generated by Django 3.2.16 on 2023-04-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_themes_frequency_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themes',
            name='frequency_word',
        ),
        migrations.AddField(
            model_name='word',
            name='frequency_word',
            field=models.BooleanField(default=False),
        ),
    ]
