# Generated by Django 3.2.16 on 2023-04-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20230407_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='themes',
            name='priority',
            field=models.IntegerField(default=100),
        ),
    ]
