# Generated by Django 3.2.16 on 2023-04-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_themes_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkRender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
        migrations.RenameModel(
            old_name='CategoryWord',
            new_name='Category',
        ),
        migrations.AddField(
            model_name='word',
            name='link',
            field=models.ManyToManyField(to='base.LinkRender'),
        ),
    ]
