# Generated by Django 3.2.16 on 2023-04-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20230407_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='link',
        ),
        migrations.AddField(
            model_name='category',
            name='link',
            field=models.ManyToManyField(default='2', to='base.LinkRender'),
        ),
    ]
