# Generated by Django 3.2.16 on 2023-04-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20230407_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='link',
            field=models.ManyToManyField(related_name='category', to='base.LinkRender'),
        ),
    ]
